### ISSUE TITLE
v6.2.2007: win: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by looooo** [NGSolve/netgen#67]
Seeing this issue here:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=188298&view=logs&jobId=e5cdccbf-4751-5a24-7406-185c9d30d021&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\bld\netgen_1595537404202\_test_env\lib\site-packages\netgen\__init__.py", line 13, in <module>
    from . import libngpy
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```

IIRC there was a similar issue some times ago which was solved by disabling `USE_NATIVE_ARCH`. Not sure why this comes up again.

**Comment by mhochsteger** [comment]
Hello,
Looking at the build logs I don't see any suspicious differences. As you found out yourself, USE_NATIVE_ARCH is correctly set to OFF as well.
Also in the source code changes I didn't see any relevant changes. Can you still build v6.2.2006? Just to make sure that changes in the build system/conda packages are not causing the issue.

I will try to reproduce this issue locally and come back to you.

Best,
Matthias

**Comment by looooo** [comment]
> Also in the source code changes I didn't see any relevant changes. Can you still build v6.2.2006? Just to make sure that changes in the build system/conda packages are not causing the issue.

yes, this is what I did for now. I switched to pulling sources with git as otherwise the version is not set correctly in the cmake-files.

**Comment by mhochsteger** [comment]
I just built your Netgen recipe ( from the use-git branch: https://github.com/looooo/netgen-feedstock/tree/use-git ), and both versions (2006 and 2007) worked fine locally (tested with conda 4.8.3 and 4.8.4).
